# Generated by Django 5.0.4 on 2026-07-18 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Album galerie',
                'verbose_name_plural': 'Albums galerie',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, help_text='Chemin statique packagé (ex: /site/img/hero-campus-1600.webp) ou URL absolue.', max_length=255)),
                ('upload', models.ImageField(blank=True, help_text='Image téléversée (prioritaire sur le chemin statique).', null=True, upload_to='website/')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('cta_label', models.CharField(blank=True, max_length=60, verbose_name='Texte du bouton')),
                ('cta_url', models.CharField(blank=True, max_length=255, verbose_name='Lien du bouton')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide du carrousel',
                'verbose_name_plural': 'Slides du carrousel',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, help_text='Chemin statique packagé (ex: /site/img/hero-campus-1600.webp) ou URL absolue.', max_length=255)),
                ('upload', models.ImageField(blank=True, help_text='Image téléversée (prioritaire sur le chemin statique).', null=True, upload_to='website/')),
                ('kind', models.CharField(choices=[('news', 'Actualité'), ('event', 'Événement')], default='news', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(blank=True, help_text="Date de l'événement (pour kind=event).", null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité / Événement',
                'verbose_name_plural': 'Actualités / Événements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('child_name', models.CharField(max_length=120)),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('desired_level', models.CharField(choices=[('garderie', 'Garderie'), ('maternelle1', 'Maternelle 1'), ('maternelle2', 'Maternelle 2'), ('ci', 'CI'), ('cp', 'CP'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('feba_online', 'FEBA Online')], max_length=20)),
                ('school_year', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('processing', 'En traitement'), ('closed', 'Clôturée')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de préinscription',
                'verbose_name_plural': 'Demandes de préinscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Faith Excellence Bilingual Academy', max_length=120)),
                ('tagline', models.CharField(blank=True, default="Développer les talents, construire l'avenir.", max_length=200)),
                ('signature', models.CharField(blank=True, default="FEBA, l'école autrement avec vous.", max_length=200)),
                ('address', models.CharField(blank=True, default='Akpakpa, Cotonou, Bénin', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp au format international (+229...). Vide = bouton masqué.', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, default='FEBA — Faith Excellence Bilingual Academy | École bilingue à Cotonou', max_length=120)),
                ('meta_description', models.CharField(blank=True, default='École bilingue français-anglais à Akpakpa, Cotonou : garderie, maternelle et primaire. Encadrement de qualité, valeurs et excellence.', max_length=300)),
                ('og_image', models.CharField(blank=True, default='/site/img/hero-campus-1600.webp', max_length=255)),
                ('stat_students', models.PositiveIntegerField(blank=True, null=True)),
                ('stat_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('stat_years', models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience")),
                ('stat_success_rate', models.PositiveIntegerField(blank=True, help_text='Taux de réussite en % (vide = masqué).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, help_text='Chemin statique packagé (ex: /site/img/hero-campus-1600.webp) ou URL absolue.', max_length=255)),
                ('upload', models.ImageField(blank=True, help_text='Image téléversée (prioritaire sur le chemin statique).', null=True, upload_to='website/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Texte alternatif (accessibilité). Repli sur la légende si vide.', max_length=200)),
                ('video_url', models.CharField(blank=True, help_text='Chemin du MP4 packagé (/site/video/...) ou URL (pour kind=video).', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.galleryalbum')),
            ],
            options={
                'verbose_name': 'Média galerie',
                'verbose_name_plural': 'Médias galerie',
                'ordering': ['album', 'order', 'id'],
            },
        ),
    ]
