# Generated by Django 5.0.4 on 2026-07-19 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='focal_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Point focal horizontal en % (0 = gauche, 50 = centre, 100 = droite).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='focal_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Point focal vertical en % (0 = haut, 50 = centre, 100 = bas).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='focal_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Point focal horizontal en % (0 = gauche, 50 = centre, 100 = droite).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='focal_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Point focal vertical en % (0 = haut, 50 = centre, 100 = bas).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='newspost',
            name='focal_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Point focal horizontal en % (0 = gauche, 50 = centre, 100 = droite).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='newspost',
            name='focal_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Point focal vertical en % (0 = haut, 50 = centre, 100 = bas).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
