# Generated by Django 5.0.4 on 2026-07-31 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0013_entity_codes_and_fha"),
        ("website", "0003_official_name_amp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "Informations générales"),
                    ("enrollment", "Inscription"),
                    ("placement_test", "Test de placement"),
                    ("payment", "Paiement"),
                    ("zoom", "Zoom / cours en direct"),
                    ("technical", "Support technique"),
                    ("pedagogical", "Question pédagogique"),
                    ("absence", "Absence"),
                    ("document", "Document"),
                    ("other", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Entité destinataire. Déterminée par la route côté serveur.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_messages",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("fr", "Français"), ("en", "English")],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="state_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="Fuseau horaire déclaré par la famille (affichage des créneaux).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="preregistration",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Entité de la demande. Fixée côté serveur (formulaire FEBA).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preregistrations",
                to="schools.school",
            ),
        ),
        migrations.CreateModel(
            name="FHAEnrollmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de dossier unique communiqué à la famille (ex: FHA-2026-0001).",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new_contact", "Nouveau contact"),
                            ("form_received", "Fiche reçue"),
                            ("test_booked", "Test réservé"),
                            ("test_done", "Test effectué"),
                            ("admission_offered", "Admission proposée"),
                            ("documents_pending", "Documents en attente"),
                            ("payment_pending", "Paiement en attente"),
                            ("enrollment_confirmed", "Inscription confirmée"),
                            ("account_activated", "Compte activé"),
                            ("student_active", "Élève actif"),
                            ("suspended", "Suspendu"),
                            ("cancelled", "Annulé"),
                        ],
                        default="form_received",
                        max_length=24,
                    ),
                ),
                ("child_last_name", models.CharField(max_length=120)),
                ("child_first_name", models.CharField(max_length=120)),
                ("child_birth_date", models.DateField()),
                ("child_city", models.CharField(blank=True, max_length=120)),
                ("child_state_province", models.CharField(blank=True, max_length=120)),
                ("child_country", models.CharField(blank=True, max_length=100)),
                ("child_current_school", models.CharField(blank=True, max_length=200)),
                ("child_grade", models.CharField(blank=True, max_length=60)),
                (
                    "child_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo facultative. Donnée de mineur : accès restreint.",
                        null=True,
                        upload_to="fha/children/",
                    ),
                ),
                ("family_origin_country", models.CharField(blank=True, max_length=120)),
                ("home_main_language", models.CharField(blank=True, max_length=120)),
                ("other_languages", models.CharField(blank=True, max_length=255)),
                (
                    "french_speakers_with_child",
                    models.CharField(
                        blank=True,
                        help_text="Personnes parlant français avec l'enfant.",
                        max_length=255,
                    ),
                ),
                (
                    "french_speakers_relation",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "french_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de valeurs FRENCH_LEVEL_CHOICES (sélections cumulables).",
                    ),
                ),
                ("french_level_notes", models.TextField(blank=True)),
                ("previous_courses", models.BooleanField(default=False)),
                ("bilingual_school", models.BooleanField(default=False)),
                ("stay_in_francophone_country", models.BooleanField(default=False)),
                (
                    "certifications_obtained",
                    models.CharField(blank=True, max_length=255),
                ),
                ("experience_duration", models.CharField(blank=True, max_length=120)),
                ("experience_comments", models.TextField(blank=True)),
                (
                    "parent_goals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste de valeurs PARENT_GOAL_CHOICES.",
                    ),
                ),
                ("parent_goals_other", models.CharField(blank=True, max_length=255)),
                ("parent1_last_name", models.CharField(max_length=120)),
                ("parent1_first_name", models.CharField(max_length=120)),
                ("parent1_relation", models.CharField(blank=True, max_length=80)),
                ("parent1_phone", models.CharField(max_length=30)),
                ("parent1_whatsapp", models.CharField(blank=True, max_length=30)),
                ("parent1_email", models.EmailField(max_length=254)),
                ("parent1_address", models.CharField(blank=True, max_length=255)),
                ("parent1_city", models.CharField(blank=True, max_length=120)),
                (
                    "parent1_state_province",
                    models.CharField(blank=True, max_length=120),
                ),
                ("parent1_country", models.CharField(blank=True, max_length=100)),
                ("parent1_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "parent1_preferred_language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("parent1_timezone", models.CharField(blank=True, max_length=64)),
                ("parent2_last_name", models.CharField(blank=True, max_length=120)),
                ("parent2_first_name", models.CharField(blank=True, max_length=120)),
                ("parent2_relation", models.CharField(blank=True, max_length=80)),
                ("parent2_phone", models.CharField(blank=True, max_length=30)),
                ("parent2_whatsapp", models.CharField(blank=True, max_length=30)),
                ("parent2_email", models.EmailField(blank=True, max_length=254)),
                ("parent2_address", models.CharField(blank=True, max_length=255)),
                ("parent2_city", models.CharField(blank=True, max_length=120)),
                (
                    "parent2_state_province",
                    models.CharField(blank=True, max_length=120),
                ),
                ("parent2_country", models.CharField(blank=True, max_length=100)),
                ("parent2_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "parent2_preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[("fr", "Français"), ("en", "English")],
                        max_length=5,
                    ),
                ),
                ("parent2_timezone", models.CharField(blank=True, max_length=64)),
                ("emergency_name", models.CharField(blank=True, max_length=160)),
                ("emergency_relation", models.CharField(blank=True, max_length=80)),
                ("emergency_phone", models.CharField(blank=True, max_length=30)),
                ("emergency_email", models.EmailField(blank=True, max_length=254)),
                ("emergency_contact_authorized", models.BooleanField(default=False)),
                (
                    "available_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Jours ISO disponibles (1=lundi … 7=dimanche).",
                    ),
                ),
                (
                    "available_time_slots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Créneaux [{'start': 'HH:MM', 'end': 'HH:MM'}] en heure locale famille.",
                    ),
                ),
                (
                    "family_timezone",
                    models.CharField(
                        blank=True,
                        help_text="Fuseau de référence des créneaux ci-dessus (IANA, ex: America/New_York).",
                        max_length=64,
                    ),
                ),
                (
                    "weekday_or_weekend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekday", "Semaine"),
                            ("weekend", "Week-end"),
                            ("both", "Les deux"),
                        ],
                        max_length=20,
                    ),
                ),
                ("availability_notes", models.TextField(blank=True)),
                ("has_computer", models.BooleanField(default=False)),
                ("has_tablet", models.BooleanField(default=False)),
                ("has_camera", models.BooleanField(default=False)),
                ("has_microphone", models.BooleanField(default=False)),
                ("has_headset", models.BooleanField(default=False)),
                ("has_internet", models.BooleanField(default=False)),
                ("can_print", models.BooleanField(default=False)),
                ("equipment_notes", models.TextField(blank=True)),
                (
                    "special_needs",
                    models.TextField(
                        blank=True,
                        help_text="CONFIDENTIEL — adaptations pédagogiques, difficultés, besoins de soutien.",
                    ),
                ),
                ("consent_rules", models.BooleanField(default=False)),
                ("consent_zoom", models.BooleanField(default=False)),
                ("consent_privacy", models.BooleanField(default=False)),
                ("consent_data_processing", models.BooleanField(default=False)),
                ("consent_photo_video", models.BooleanField(default=False)),
                ("consent_communications", models.BooleanField(default=False)),
                ("consent_payment_policy", models.BooleanField(default=False)),
                ("consent_annual_commitment", models.BooleanField(default=False)),
                ("consent_parental_authorization", models.BooleanField(default=False)),
                (
                    "consents_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version des textes de consentement acceptés (traçabilité).",
                        max_length=20,
                    ),
                ),
                ("consents_accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recommended_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior_roots", "Junior Roots (6-9 ans)"),
                            ("french_explorers", "French Explorers (10-15 ans)"),
                            ("french_ambassadors", "French Ambassadors (16-17 ans)"),
                        ],
                        help_text="Groupe recommandé après test de placement.",
                        max_length=24,
                    ),
                ),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="Toujours FEBA_FHA. Déterminé par la route, jamais par le client.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fha_applications",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche d'inscription FEBA FHA",
                "verbose_name_plural": "Fiches d'inscription FEBA FHA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FHAApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=24)),
                ("to_status", models.CharField(max_length=24)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fha_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="website.fhaenrollmentapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Changement d'état de dossier FHA",
                "verbose_name_plural": "Changements d'état de dossier FHA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="fhaenrollmentapplication",
            constraint=models.UniqueConstraint(
                fields=(
                    "entity",
                    "parent1_email",
                    "child_first_name",
                    "child_last_name",
                    "child_birth_date",
                ),
                name="uniq_fha_application_child_per_parent",
            ),
        ),
    ]
