# Generated by Django 5.0.4 on 2026-07-31 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0013_entity_codes_and_fha"),
        ("virtualclass", "0002_attendance_enrollment"),
        ("website", "0005_backfill_form_entities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="preregistration",
            name="desired_level",
            field=models.CharField(
                choices=[
                    ("garderie", "Garderie"),
                    ("maternelle1", "Maternelle 1"),
                    ("maternelle2", "Maternelle 2"),
                    ("ci", "CI"),
                    ("cp", "CP"),
                    ("ce1", "CE1"),
                    ("ce2", "CE2"),
                    ("cm1", "CM1"),
                    ("cm2", "CM2"),
                    ("feba_online", "FEBA French Heritage Academy"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FHAPlacementTestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de dossier de test (ex: FHA-TEST-2026-0001).",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Demande reçue"),
                            ("scheduled", "Créneau confirmé"),
                            ("reminded", "Rappel envoyé"),
                            ("completed", "Test effectué"),
                            ("no_show", "Absence"),
                            ("rescheduled", "Reprogrammé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("child_first_name", models.CharField(max_length=120)),
                ("child_last_name", models.CharField(max_length=120)),
                ("child_birth_date", models.DateField()),
                ("child_country", models.CharField(blank=True, max_length=100)),
                ("child_state_province", models.CharField(blank=True, max_length=120)),
                ("parent_first_name", models.CharField(max_length=120)),
                ("parent_last_name", models.CharField(max_length=120)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(max_length=30)),
                ("parent_whatsapp", models.CharField(blank=True, max_length=30)),
                (
                    "parent_timezone",
                    models.CharField(
                        blank=True,
                        help_text="Fuseau IANA de la famille : les créneaux lui sont affichés dans cette heure locale.",
                        max_length=64,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "estimated_level",
                    models.CharField(
                        choices=[
                            ("none", "Ne comprend pas le français"),
                            ("few_words", "Comprend quelques mots"),
                            ("understands", "Comprend mais répond en anglais"),
                            ("speaks_a_little", "Parle un peu"),
                            ("speaks_well", "Parle bien"),
                            ("unknown", "Je ne sais pas"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("previous_experience", models.TextField(blank=True)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                ("alternate_date", models.DateField(blank=True, null=True)),
                ("alternate_time", models.TimeField(blank=True, null=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Créneau confirmé, stocké en UTC.",
                        null=True,
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(
                        blank=True,
                        help_text="CONFIDENTIEL — besoin particulier signalé par la famille.",
                    ),
                ),
                (
                    "consent_video",
                    models.BooleanField(
                        default=False,
                        help_text="Consentement à la participation en visioconférence.",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fiche d'inscription associée, si la famille a poursuivi le parcours.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placement_tests",
                        to="website.fhaenrollmentapplication",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="Toujours FEBA_FHA. Déterminé par la route, jamais par le client.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fha_placement_requests",
                        to="schools.school",
                    ),
                ),
                (
                    "meeting_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Salle de visioconférence privée du test.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placement_tests",
                        to="virtualclass.virtualroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de test de placement FEBA FHA",
                "verbose_name_plural": "Demandes de test de placement FEBA FHA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FHAPlacementTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listening",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Non évalué"),
                            (1, "Débutant"),
                            (2, "En cours"),
                            (3, "Acquis"),
                            (4, "Avancé"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "speaking",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Non évalué"),
                            (1, "Débutant"),
                            (2, "En cours"),
                            (3, "Acquis"),
                            (4, "Avancé"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "vocabulary",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Non évalué"),
                            (1, "Débutant"),
                            (2, "En cours"),
                            (3, "Acquis"),
                            (4, "Avancé"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "reading",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Non évalué"),
                            (1, "Débutant"),
                            (2, "En cours"),
                            (3, "Acquis"),
                            (4, "Avancé"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "writing",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Non évalué"),
                            (1, "Débutant"),
                            (2, "En cours"),
                            (3, "Acquis"),
                            (4, "Avancé"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Non évalué"),
                            (1, "Débutant"),
                            (2, "En cours"),
                            (3, "Acquis"),
                            (4, "Avancé"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "recommended_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior_roots", "Junior Roots (6-9 ans)"),
                            ("french_explorers", "French Explorers (10-15 ans)"),
                            ("french_ambassadors", "French Ambassadors (16-17 ans)"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "starting_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Débutant"),
                            ("intermediate", "Intermédiaire"),
                            ("advanced", "Avancé"),
                        ],
                        max_length=16,
                    ),
                ),
                ("priority_objectives", models.TextField(blank=True)),
                ("assessor_notes", models.TextField(blank=True)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fha_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="website.fhaplacementtestrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de test de placement FHA",
                "verbose_name_plural": "Résultats de test de placement FHA",
            },
        ),
        migrations.AddConstraint(
            model_name="fhaplacementtestrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["requested", "scheduled", "reminded"])
                ),
                fields=(
                    "entity",
                    "parent_email",
                    "child_first_name",
                    "child_last_name",
                    "child_birth_date",
                ),
                name="uniq_active_placement_request_per_child",
            ),
        ),
    ]
