# Generated by Django 5.0.4 on 2026-07-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_preregistration_desired_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryalbum",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Description (EN)"
            ),
        ),
        migrations.AddField(
            model_name="galleryalbum",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="alt_text_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Texte alternatif (EN)"
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="caption_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Légende (EN)"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="cta_label_en",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Texte du bouton (EN)"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="subtitle_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Sous-titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="newspost",
            name="body_en",
            field=models.TextField(blank=True, verbose_name="Contenu (EN)"),
        ),
        migrations.AddField(
            model_name="newspost",
            name="excerpt_en",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Résumé (EN)"
            ),
        ),
        migrations.AddField(
            model_name="newspost",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                default="French-English bilingual school in Akpakpa, Cotonou: nursery, kindergarten and primary. Quality teaching, values and excellence.",
                max_length=300,
                verbose_name="Méta-description (EN)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="opening_hours_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Horaires (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline_en",
            field=models.CharField(
                blank=True,
                default="Developing talent, building the future.",
                max_length=200,
                verbose_name="Slogan (EN)",
            ),
        ),
    ]
