# Generated by Django 5.0.4 on 2026-08-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_galleryalbum_description_en_galleryalbum_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="sheet_error",
            field=models.TextField(
                blank=True,
                help_text="Cause EXACTE d'un échec de production de la fiche.",
            ),
        ),
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="sheet_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="sheet_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="sheet_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="sheet_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="sheet_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
