# Generated by Django 5.0.4 on 2026-08-01 16:09

import apps.website.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_fhaenrollmentapplication_sheet_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fhaenrollmentapplication",
            name="child_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo facultative. Donnée de mineur : stockage privé, accès restreint.",
                null=True,
                storage=apps.website.private_storage.private_storage,
                upload_to="fha/children/",
            ),
        ),
    ]
