# Generated by Django 5.0.4 on 2026-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_preregistration_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fhaenrollmentapplication",
            name="desired_plan",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard — 699 $/an"),
                    ("PREMIUM", "Premium — 999 $/an"),
                    ("EXCELLENCE", "Excellence — 1 299 $/an"),
                    ("UNDECIDED", "Non décidé"),
                ],
                default="UNDECIDED",
                help_text="Formule annuelle souhaitée, déclarée par la famille.",
                max_length=12,
            ),
        ),
    ]
