# Generated by Django 5.0.4 on 2026-07-16 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_purge_auto_zero_grades'),
        ('students', '0006_alter_student_exit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text="Inscription annuelle de l'élève correspondant à cette note (cohérence élève ↔ classe ↔ année).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='students.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='note_coefficient',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='note_type',
            field=models.CharField(choices=[('devoir', 'Devoir'), ('interrogation', 'Interrogation'), ('controle', 'Contrôle'), ('examen', 'Examen'), ('tp', 'Travaux Pratiques'), ('autre', 'Autre')], default='devoir', max_length=20),
        ),
    ]
