# Generated by Django 5.0.4 on 2026-07-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_alter_grade_enrollment_alter_grade_note_coefficient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='note_type',
            field=models.CharField(choices=[('devoir', 'Devoir'), ('interrogation', 'Interrogation / Devoir de classe'), ('controle', 'Contrôle'), ('examen', 'Examen / Évaluation'), ('tp', 'Travaux Pratiques'), ('autre', 'Autre')], default='devoir', max_length=20),
        ),
    ]
