# Generated by Django 5.0.4 on 2026-07-26 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_assessment_weight_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='note_coefficient',
            field=models.PositiveSmallIntegerField(default=1, help_text="Poids de l'évaluation — toujours 1 (règle FEBA V8).", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
