# Generated by Django 5.0.4 on 2026-08-02 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0014_remove_school_currency_school_currency_code_and_more"),
        ("students", "0006_alter_student_exit_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyStudentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField(help_text="1 à 12.")),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "reference",
                    models.CharField(blank=True, max_length=48, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("generated", "Généré"),
                            ("ready", "Prêt à envoyer"),
                            ("sending", "Envoi en cours"),
                            ("sent", "Envoyé"),
                            ("failed", "Échec"),
                            ("cancelled", "Annulé"),
                            ("archived", "Archivé"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("generated_data", models.JSONField(blank=True, default=dict)),
                ("editable_content", models.JSONField(blank=True, default=dict)),
                ("pdf_path", models.CharField(blank=True, max_length=255)),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Adresses réellement visées par la dernière tentative.",
                    ),
                ),
                ("attempts_count", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Académie propriétaire. Fixée d'après l'élève.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_reports",
                        to="schools.school",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_reports",
                        to="schools.schoolyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_reports_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport mensuel",
                "verbose_name_plural": "Rapports mensuels",
                "ordering": ["-year", "-month", "student__last_name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReportAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("succeeded", models.BooleanField(default=False)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                (
                    "used_real_provider",
                    models.BooleanField(
                        default=False,
                        help_text="Faux quand le message a seulement été écrit dans la console ou capturé localement.",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_report_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="monthly_reports.monthlystudentreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative d'envoi",
                "verbose_name_plural": "Tentatives d'envoi",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monthlystudentreport",
            index=models.Index(
                fields=["academy", "year", "month"],
                name="monthly_rep_academy_0c62d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlystudentreport",
            index=models.Index(
                fields=["status", "scheduled_at"], name="monthly_rep_status_3643ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlystudentreport",
            constraint=models.UniqueConstraint(
                fields=("academy", "student", "year", "month", "version"),
                name="rapport_mensuel_unique_par_periode_et_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlystudentreport",
            constraint=models.CheckConstraint(
                check=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="rapport_mensuel_mois_valide",
            ),
        ),
    ]
