# Generated by Django 5.0.4 — BUG N°8 (préfixe matricule) + résorption du
# drift modèle↔migrations préexistant sur Room/RoomType/School.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_single_current_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="matricule_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Préfixe court des matricules (ex: FEBA). Vide = dérivé du slug.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="custom_type_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="schools.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="school",
            name="subscription_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes internes (équipe commerciale/support), non visibles par l'établissement.",
            ),
        ),
    ]
