# Generated by Django 5.0.4 on 2026-07-31 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0011_official_school_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Identifiant interne STABLE de l'entité (ex: FEBA, FEBA_FHA). Utilisé par la logique métier — ne jamais le dériver du nom affiché.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="currency",
            field=models.CharField(
                default="XOF",
                help_text="Devise des paiements, factures et reçus de cette entité (ex: XOF, USD).",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="default_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                help_text="Langue par défaut des documents et notifications de l'entité.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("campus", "École présentielle"),
                    ("online", "Académie en ligne"),
                ],
                default="campus",
                help_text="Détermine les fonctionnalités par défaut (présentiel vs académie en ligne).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Dénomination légale complète (documents officiels, contrats, factures).",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Réglages administrables de l'entité (features, textes, politiques).",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="timezone",
            field=models.CharField(
                default="Africa/Porto-Novo",
                help_text="Fuseau horaire de référence administrative (ex: America/New_York pour FEBA FHA).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Numéro WhatsApp au format international. Vide = bouton WhatsApp masqué.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EntitySwitchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switches_from",
                        to="schools.school",
                    ),
                ),
                (
                    "to_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = bascule vers le mode « Toutes les entités ».",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switches_to",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_switches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Changement d'entité active",
                "verbose_name_plural": "Changements d'entité active",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Rôle porté par cette appartenance (mêmes valeurs que CustomUser.role).",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspendue"),
                            ("revoked", "Révoquée"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Appartenance principale : entité par défaut à la connexion.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appartenance à une entité",
                "verbose_name_plural": "Appartenances aux entités",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="uniq_membership_user_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="uniq_primary_membership_per_user",
            ),
        ),
    ]
