# Generated by Django 5.0.4 on 2026-07-31 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_class_subjects"),
        ("schedule", "0002_alter_classschedule_id"),
        ("schools", "0013_entity_codes_and_fha"),
        ("subjects", "0005_alter_subject_options"),
        ("teachers", "0001_initial"),
        ("virtualclass", "0002_attendance_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineSessionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        help_text="Jour de la semaine EN UTC — le jour local peut différer.",
                    ),
                ),
                (
                    "start_time_utc",
                    models.TimeField(
                        help_text="Heure de début en UTC. Référence unique de la séance."
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, help_text="Durée en minutes (1 à 480)."
                    ),
                ),
                (
                    "display_timezone",
                    models.CharField(
                        default="America/New_York",
                        help_text="Fuseau de référence pour l'affichage administratif. N'influence PAS l'heure réelle de la séance.",
                        max_length=64,
                    ),
                ),
                (
                    "reminders_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Envoie un rappel aux familles avant chaque séance.",
                    ),
                ),
                (
                    "reminder_minutes_before",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Délai du rappel avant la séance, en minutes.",
                    ),
                ),
                ("recurrent", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Académie en ligne propriétaire de la séance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_sessions",
                        to="schools.school",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        help_text="Groupe en ligne (Junior Roots, French Explorers…).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_sessions",
                        to="classes.class",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_sessions",
                        to="schools.schoolyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_sessions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_sessions",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "virtual_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Salle virtuelle FEBA. Vide = lien à créer avant la séance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_sessions",
                        to="virtualclass.virtualroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance en ligne (FEBA FHA)",
                "verbose_name_plural": "Séances en ligne (FEBA FHA)",
                "ordering": ["day_of_week", "start_time_utc"],
            },
        ),
        migrations.AddConstraint(
            model_name="onlinesessionschedule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("duration_minutes__gte", 1), ("duration_minutes__lte", 480)
                ),
                name="online_session_duration_between_1_and_480",
            ),
        ),
        migrations.AddConstraint(
            model_name="onlinesessionschedule",
            constraint=models.CheckConstraint(
                check=models.Q(("reminder_minutes_before__lte", 1440)),
                name="online_session_reminder_at_most_24h",
            ),
        ),
        migrations.AddConstraint(
            model_name="onlinesessionschedule",
            constraint=models.UniqueConstraint(
                fields=("group", "day_of_week", "start_time_utc"),
                name="uniq_online_session_group_slot",
            ),
        ),
    ]
