# Generated by Django 5.0.4 on 2026-08-01 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_id"),
        ("schools", "0014_remove_school_currency_school_currency_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "purpose",
                    models.CharField(
                        help_text="Nature de l'envoi (ex: fha_enrollment_ack, fha_admin_alert).",
                        max_length=64,
                    ),
                ),
                ("subject_reference", models.CharField(blank=True, max_length=64)),
                ("to_email", models.EmailField(max_length=254)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("language", models.CharField(blank=True, max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente d'envoi"),
                            ("accepted", "Accepté par le fournisseur"),
                            ("sent", "Envoyé"),
                            ("failed", "Échec"),
                            ("retry", "Nouvel essai programmé"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Message d'erreur EXACT du fournisseur. Jamais reformulé.",
                    ),
                ),
                ("backend", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Académie émettrice. Détermine l'expéditeur et le destinataire interne.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_deliveries",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envoi d'e-mail",
                "verbose_name_plural": "Envois d'e-mail",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "status"],
                        name="notificatio_entity__8b3644_idx",
                    ),
                    models.Index(
                        fields=["purpose", "subject_reference"],
                        name="notificatio_purpose_c598ea_idx",
                    ),
                ],
            },
        ),
    ]
