# Generated by Django 6.0.4 on 2026-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
        ('schools', '0002_room'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bulletin',
            name='unique_bulletin',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('student', 'school_year', 'period')},
        ),
    ]
