# Generated by Django 5.0.4 on 2026-07-16 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_bulletin_enrollment'),
        ('students', '0006_alter_student_exit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text="Inscription annuelle de l'élève correspondant à ce bulletin.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='students.studentenrollment'),
        ),
    ]
