"""
Tests — Salles virtuelles (module virtualclass).

Couvre :
  1. Isolation multi-tenant : un admin ne voit pas les salles d'un autre établissement
  2. Visibilité par rôle : un élève ne voit que les salles de sa classe + salles générales
  3. Création réservée aux enseignants et administrateurs (403 pour un élève)
  4. room_code généré automatiquement, unique et non vide
  5. join/ enregistre une participation et passe le statut à "live"
"""
from django.test import TestCase
from rest_framework.test import APIClient
from rest_framework import status

from apps.accounts.models import CustomUser
from apps.classes.models import Class
from apps.schools.models import School, SchoolYear, Level
from apps.students.models import Student
from apps.virtualclass.models import VirtualRoom, VirtualRoomAttendance


def make_school(name="Ecole Test"):
    return School.objects.create(name=name, address="Adresse")


def make_user(email, role, school=None, password="Pass1234!"):
    return CustomUser.objects.create_user(
        username=email.split("@")[0], email=email, password=password,
        role=role, first_name="T", last_name="U", school=school,
    )


def auth(client, email, password="Pass1234!"):
    resp = client.post("/api/auth/login/", {"email": email, "password": password})
    token = resp.data.get("access", "")
    client.credentials(HTTP_AUTHORIZATION=f"Bearer {token}")


class VirtualRoomTenantTests(TestCase):
    def setUp(self):
        self.school_a = make_school("Ecole A")
        self.school_b = make_school("Ecole B")
        self.admin_a = make_user("admin.a@test.bj", "admin", self.school_a)
        self.admin_b = make_user("admin.b@test.bj", "admin", self.school_b)
        self.room_a = VirtualRoom.objects.create(school=self.school_a, name="Salle A", created_by=self.admin_a)
        self.room_b = VirtualRoom.objects.create(school=self.school_b, name="Salle B", created_by=self.admin_b)
        self.client = APIClient()

    def test_admin_sees_only_own_school_rooms(self):
        auth(self.client, "admin.a@test.bj")
        resp = self.client.get("/api/virtual-rooms/")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        results = resp.data.get("results", resp.data)
        names = [r["name"] for r in results]
        self.assertIn("Salle A", names)
        self.assertNotIn("Salle B", names)

    def test_room_code_autogenerated_and_unique(self):
        self.assertTrue(self.room_a.room_code)
        self.assertTrue(self.room_b.room_code)
        self.assertNotEqual(self.room_a.room_code, self.room_b.room_code)


class VirtualRoomRoleTests(TestCase):
    def setUp(self):
        self.school = make_school()
        self.admin = make_user("admin@test.bj", "admin", self.school)
        self.year = SchoolYear.objects.create(
            school=self.school, name="2025-2026",
            start_date="2025-09-01", end_date="2026-06-30", is_current=True,
        )
        self.level = Level.objects.create(school=self.school, name="6eme", order=1, cycle="college")
        self.cls_a = Class.objects.create(name="6eme A", level=self.level, school_year=self.year)
        self.cls_b = Class.objects.create(name="6eme B", level=self.level, school_year=self.year)
        self.student_user = make_user("eleve@test.bj", "student", self.school)
        self.student = Student.objects.create(
            user=self.student_user, school=self.school,
            first_name="Ali", last_name="Zog", current_class=self.cls_a,
        )
        self.room_general = VirtualRoom.objects.create(school=self.school, name="Reunion generale")
        self.room_a = VirtualRoom.objects.create(school=self.school, name="Cours 6eme A", class_obj=self.cls_a)
        self.room_b = VirtualRoom.objects.create(school=self.school, name="Cours 6eme B", class_obj=self.cls_b)
        self.client = APIClient()

    def test_student_sees_only_own_class_and_general(self):
        auth(self.client, "eleve@test.bj")
        resp = self.client.get("/api/virtual-rooms/")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        names = {r["name"] for r in resp.data.get("results", resp.data)}
        self.assertIn("Reunion generale", names)
        self.assertIn("Cours 6eme A", names)
        self.assertNotIn("Cours 6eme B", names)

    def test_student_cannot_create_room(self):
        auth(self.client, "eleve@test.bj")
        resp = self.client.post("/api/virtual-rooms/", {"name": "Interdit"})
        self.assertEqual(resp.status_code, status.HTTP_403_FORBIDDEN)

    def test_admin_can_create_room(self):
        auth(self.client, "admin@test.bj")
        resp = self.client.post("/api/virtual-rooms/", {"name": "Conseil de classe"})
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertTrue(resp.data["room_code"])
        self.assertEqual(VirtualRoom.objects.get(pk=resp.data["id"]).school_id, self.school.id)

    def test_join_records_attendance_and_sets_live(self):
        auth(self.client, "eleve@test.bj")
        resp = self.client.post(f"/api/virtual-rooms/{self.room_a.id}/join/")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        self.room_a.refresh_from_db()
        self.assertEqual(self.room_a.status, "live")
        self.assertEqual(
            VirtualRoomAttendance.objects.filter(room=self.room_a, user=self.student_user).count(), 1,
        )
