# Generated by Django 5.0.4 on 2026-09-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualclass", "0002_attendance_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualroom",
            name="target_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Rôles pouvant rejoindre la salle (admin, teacher, student, parent). Vide = tous les rôles autorisés par ailleurs.",
                verbose_name="Rôles autorisés",
            ),
        ),
    ]
