# Generated by Django 5.0.4 on 2026-07-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_official_school_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.CharField(blank=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='high', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('ignored', 'Ignoré'), ('reopened', 'Réouvert')], default='new', max_length=15)),
                ('module', models.CharField(blank=True, max_length=80)),
                ('frontend_route', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text="Fichier:ligne (fonction) d'origine.", max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('attempted_action', models.CharField(blank=True, max_length=255)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('release', models.CharField(blank=True, max_length=60)),
                ('fingerprint', models.CharField(db_index=True, max_length=40)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_incidents', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident technique',
                'verbose_name_plural': 'Incidents techniques',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='incidents_t_status_4c6153_idx'), models.Index(fields=['severity'], name='incidents_t_severit_8988ec_idx')],
            },
        ),
    ]
