# Generated by Django 5.0.4 on 2026-07-18 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_preferred_language'),
        ('schools', '0010_feba_matricule_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="L'utilisateur doit changer son mot de passe à la prochaine connexion."),
        ),
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by_email', models.EmailField(help_text="Copie de l'email de l'auteur (résiste à la suppression du compte).", max_length=254)),
                ('target_email', models.EmailField(max_length=254)),
                ('target_role', models.CharField(max_length=12)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_resets_performed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réinitialisation de mot de passe',
                'verbose_name_plural': 'Réinitialisations de mot de passe',
                'ordering': ['-performed_at'],
            },
        ),
    ]
