# Generated by Django 5.0.4 on 2026-07-31 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_must_change_password_passwordresetlog"),
        ("schools", "0013_entity_codes_and_fha"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Entité active du superadmin (NULL = mode « toutes les entités »). Modifiable uniquement via l'endpoint de bascule, qui journalise le changement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_users",
                to="schools.school",
            ),
        ),
    ]
