# Generated by Django 5.0.4 on 2026-07-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_language_helptext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Matière'},
        ),
    ]
