# Generated by Django 5.0.4 on 2026-04-17 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.level')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.schoolyear')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['name'],
            },
        ),
    ]
