# Generated by Django 5.0.4 on 2026-09-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_class_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="language_track",
            field=models.CharField(
                choices=[
                    ("BILINGUAL", "Bilingue (français et anglais)"),
                    ("FRANCOPHONE", "Francophone"),
                    ("ANGLOPHONE", "Anglophone"),
                ],
                default="BILINGUAL",
                help_text="Détermine les matières attendues et la forme du bulletin. « Bilingue » est la valeur par défaut : c'est le fonctionnement historique de FEBA, et il reste inchangé.",
                max_length=20,
                verbose_name="Parcours linguistique",
            ),
        ),
    ]
