# Generated by Django 5.0.4 on 2026-08-01 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0014_remove_school_currency_school_currency_code_and_more"),
        ("students", "0006_alter_student_exit_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_sequences",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séquence de numérotation",
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=50)),
                ("template_version", models.PositiveIntegerField(default=1)),
                (
                    "template_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Empreinte du gabarit (coordonnées comprises) au moment du rendu.",
                        max_length=64,
                    ),
                ),
                (
                    "background_sha256",
                    models.CharField(
                        blank=True,
                        help_text="Empreinte du fond verrouillé réellement utilisé.",
                        max_length=64,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Numéro officiel, attribué à l'émission uniquement.",
                        max_length=40,
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Champs variables rendus. Conservés pour pouvoir rejouer le document.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("to_validate", "À valider"),
                            ("validated", "Validé"),
                            ("issued", "Émis"),
                            ("revoked", "Révoqué"),
                            ("replaced", "Remplacé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Chemin RELATIF dans le stockage privé. Jamais une URL publique.",
                        max_length=500,
                    ),
                ),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="schools.school",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document que celui-ci remplace. L'ancien reste consultable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="documents.generateddocument",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to="schools.schoolyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_documents",
                        to="students.student",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document officiel",
                "verbose_name_plural": "Documents officiels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("detail", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="documents.generateddocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement document",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentnumbersequence",
            constraint=models.UniqueConstraint(
                fields=("academy", "template_id", "year"), name="uniq_document_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(
                fields=["academy", "status"], name="documents_g_academy_ebc41a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(
                fields=["student", "template_id"], name="documents_g_student_4ba6dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="generateddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="uniq_document_number",
            ),
        ),
    ]
