# Generated by Django 5.0.4 on 2026-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentmatriculesequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exit_notes',
            field=models.TextField(blank=True),
        ),
    ]
