# Generated by Django 5.0.4 on 2026-04-17 01:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('inscription', 'Inscription'), ('mensualite', 'Mensualité'), ('cantine', 'Cantine'), ('transport', 'Transport'), ('other', 'Autre')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mtn_momo', 'MTN MoMo'), ('moov_money', 'Moov Money'), ('card', 'Carte bancaire')], default='cash', max_length=15)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('is_confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-payment_date'],
            },
        ),
    ]
