# Generated by Django 6.0.4 on 2026-04-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_soft_delete'),
        ('schools', '0002_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Paiement'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolyear'),
        ),
    ]
