# Generated by Django 5.0.4 on 2026-07-16 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_enrollment'),
        ('students', '0006_alter_student_exit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text="Inscription annuelle de l'élève correspondant à ce paiement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='students.studentenrollment'),
        ),
    ]
