"""
payments/0007 — chaque paiement porte désormais sa devise.

Les 270 paiements existants sont tous rattachés à FEBA, qui facture en
francs CFA : leur devise n'est donc pas ambiguë et peut être posée sans
risque. Le montant en unité mineure est dérivé du montant décimal existant
selon le nombre de décimales de CETTE devise — le franc CFA n'ayant pas de
subdivision, 50 000 FCFA valent 50 000 unités mineures, pas 5 000 000.

Aucune conversion de valeur n'a lieu ici : on ne transforme pas un montant
historique, on lui attache l'unité qui était déjà la sienne.
"""
# Generated by Django 5.0.4 on 2026-08-01 02:41

from django.conf import settings
from django.db import migrations, models


def backfill_currency_and_minor(apps, schema_editor):
    """Attache à chaque paiement la devise de l'académie de son élève."""
    from decimal import Decimal, ROUND_HALF_UP

    Payment = apps.get_model("payments", "Payment")
    decimals = {"XOF": 0, "USD": 2}

    payments = Payment.objects.select_related("student__school").iterator()
    for payment in payments:
        school = getattr(getattr(payment, "student", None), "school", None)
        code = (getattr(school, "currency_code", None) or "XOF").upper()
        places = decimals.get(code, 2)
        amount = Decimal(str(payment.amount or 0))
        minor = int((amount * (10 ** places)).quantize(Decimal("1"), rounding=ROUND_HALF_UP))
        Payment.objects.filter(pk=payment.pk).update(currency=code, amount_minor=minor)


def clear_currency_and_minor(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.all().update(currency="XOF", amount_minor=0)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_enrollment"),
        ("schools", "0014_remove_school_currency_school_currency_code_and_more"),
        ("students", "0006_alter_student_exit_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_minor",
            field=models.BigIntegerField(
                default=0,
                help_text="Montant en unité mineure (cents pour USD, franc pour XOF). Valeur de référence.",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="XOF",
                help_text="Devise du paiement. Imposée par l'académie de l'élève : elle n'est jamais lue depuis le formulaire.",
                max_length=3,
            ),
        ),
        migrations.RunPython(backfill_currency_and_minor, clear_currency_and_minor),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_minor__gte", 0)),
                name="payment_amount_minor_not_negative",
            ),
        ),
    ]
