# Generated by Django 5.0.4 on 2026-08-01 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_amount_minor_payment_currency_and_more"),
        ("schools", "0014_remove_school_currency_school_currency_code_and_more"),
        ("students", "0006_alter_student_exit_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        help_text="Nature des frais (mensualite, inscription, cantine…).",
                        max_length=15,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé affiché au payeur. À défaut, le type est utilisé.",
                        max_length=120,
                    ),
                ),
                (
                    "amount_minor",
                    models.BigIntegerField(
                        help_text="Montant en unité mineure (cents pour USD, franc pour XOF)."
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="XOF", editable=False, max_length=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Académie qui publie ce tarif — impose la devise.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedules",
                        to="schools.school",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Niveau concerné. Vide = tous niveaux.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedules",
                        to="schools.level",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="Année concernée. Vide = tarif permanent, toutes années.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedules",
                        to="schools.schoolyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Grille tarifaire",
                "ordering": ["academy", "payment_type", "level"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        default="mensualite",
                        help_text="Nature de la somme réglée — reprise sur le Payment créé.",
                        max_length=15,
                    ),
                ),
                (
                    "amount_source",
                    models.CharField(
                        default="fee_schedule",
                        help_text="Origine du montant : « fee_schedule » (grille publiée) ou « staff » (saisi par l'administration). Jamais « client » : un montant transmis par le navigateur n'est pas une autorité.",
                        max_length=20,
                    ),
                ),
                (
                    "amount_minor",
                    models.BigIntegerField(
                        help_text="Montant en unité mineure (cents pour USD)."
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("amount_refunded_minor", models.BigIntegerField(default=0)),
                ("provider", models.CharField(default="stripe", max_length=20)),
                (
                    "provider_session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifiant de la session de paiement hébergée.",
                        max_length=255,
                    ),
                ),
                (
                    "provider_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifiant du PaymentIntent — clé du rapprochement.",
                        max_length=255,
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        blank=True,
                        help_text="Statut brut renvoyé par le prestataire, conservé tel quel pour l'audit.",
                        max_length=50,
                    ),
                ),
                (
                    "provider_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées NON SENSIBLES (jamais de données de carte).",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("pending", "En attente"),
                            (
                                "action_required",
                                "Action requise (authentification bancaire)",
                            ),
                            ("processing", "Traitement en cours"),
                            ("succeeded", "Réussi"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                            ("partially_refunded", "Partiellement remboursé"),
                            ("refunded", "Totalement remboursé"),
                            ("disputed", "Contesté"),
                        ],
                        default="created",
                        max_length=25,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        help_text="Académie propriétaire — impose la devise.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="schools.school",
                    ),
                ),
                (
                    "fee_schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ligne tarifaire réglée. Vide lorsqu'un membre de l'administration a saisi un montant hors grille.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.feeschedule",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur qui a lancé le paiement (parent le plus souvent).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Encaissement constaté, créé une seule fois à la réussite.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_transaction",
                        to="payments.payment",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to="schools.schoolyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction carte",
                "verbose_name_plural": "Transactions carte",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="stripe", max_length=20)),
                (
                    "event_id",
                    models.CharField(
                        help_text="Identifiant unique de l'événement chez le prestataire.",
                        max_length=255,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçu"),
                            ("processed", "Traité"),
                            ("ignored", "Ignoré (doublon ou type non géré)"),
                            ("failed", "Échec de traitement"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement webhook",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_minor__gt", 0)), name="fee_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("level__isnull", False), ("school_year__isnull", False)
                ),
                fields=("academy", "payment_type", "school_year", "level"),
                name="uniq_fee_year_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("level__isnull", True), ("school_year__isnull", False)
                ),
                fields=("academy", "payment_type", "school_year"),
                name="uniq_fee_year_any_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("level__isnull", False), ("school_year__isnull", True)
                ),
                fields=("academy", "payment_type", "level"),
                name="uniq_fee_any_year_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("level__isnull", True), ("school_year__isnull", True)
                ),
                fields=("academy", "payment_type"),
                name="uniq_fee_permanent",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["academy", "status"], name="payments_pa_academy_3165b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider", "provider_intent_id"],
                name="payments_pa_provide_df255b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_minor__gt", 0)),
                name="transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("amount_refunded_minor__lte", models.F("amount_minor"))
                ),
                name="transaction_refund_not_over_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_refunded_minor__gte", 0)),
                name="transaction_refund_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_id"), name="uniq_webhook_event_per_provider"
            ),
        ),
    ]
