# Generated by Django 5.0.4 on 2026-08-03 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_feeschedule_paymenttransaction_webhookevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text='Devise source, ex. USD.', max_length=3)),
                ('quote_currency', models.CharField(help_text='Devise cible, ex. XOF.', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text="Combien d'unités de quote_currency pour 1 unité de base_currency.", max_digits=18)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate, help_text="Date à partir de laquelle ce taux s'applique.")),
                ('source', models.CharField(blank=True, help_text="D'où vient ce taux (ex. « BCEAO », « saisie manuelle »).", max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'effective_date'], name='payments_ex_base_cu_084464_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gt', 0)), name='exchange_rate_positive'),
        ),
    ]
